apiVersion: v1
kind: Service
metadata:
  name: teamcity
  labels:
    app: teamcity
spec:
  ports:
  - port: 8111
    targetPort: teamcity-port
  selector:
    app: teamcity

---

apiVersion: v1
kind: Pod
metadata:
  name: teamcity
  labels:
    app: teamcity
spec:
  containers:
  - image: jetbrains/teamcity-server
    name: teamcity-server
    ports:
    - name: teamcity-port
      containerPort: 8111