apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    role: master
spec:
  ports:
  - port: 6379
    targetPort: redis-port
  selector:
    app: redis
    role: master

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    role: master
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - name: redis-port
      containerPort: 6379