apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    role: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        role: server
    spec:        
      containers:
      - image: datadog/docker-dd-agent:latest
        name: dd-agent