apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    role: server
spec:
  type: LoadBalancer
  loadBalancerIP: 104.155.123.156
  ports:  
  - port: 3000
    targetPort: backend
  selector:
    app: backend
    role: server